from setuptools import find_packages, setup
# 1234c
setup(
    name='codecheck',
    version='1.0.0',
    packages=[
        'codecheck',
        'codecheck.user',
        'codecheck.database',
        'codecheck.manage',
        'codecheck.utils',
        'codecheck.monitor',
        "codecheck.ai",
        "codecheck.analyser",
        "codecheck.emailSender"
        ],
    include_package_data=True,
    zip_safe=False,
    install_requires=[
        "flask",
        "PyMySql",
        "flask_cors",
        "sqlalchemy",
        "DButils",
        "psutil",
        "flask_apscheduler",
        "erniebot",
        "py7zr",
        "rarfile"
    ],
)